:reporttype:    HOWTO
:reporttitle:   Configuring a .netrc file for automatic user authentication with bitbucket.org
:author:        David Kirwan
:email:         dkirwan@tssg.org
:group:         Telecommunications Software and Systems Group (TSSG)
:address:       Waterford Institute of Technology, West Campus, Carriganore, Waterford, Ireland
:revdate:       September 10, 2012
:revnumber:     0.1
:docdate:       September 10, 2012
:description:   HOWTO configure the .netrc file to allow automatic user credentials authentication with https://bitbucket.org
:legal:         (C) Waterford Institute of Technology
:encoding:      iso-8859-1
:toc:


== Introduction ==
The purpose of this document is to explain the steps required to enable automatic user credentials authentication with
https://bitbucket.org or any other git repository system which is authenticated by means of a username and password.

[NOTE]
You do not need this system to work with https://github.com for instance, as github uses SSH keys to authenticate with
the repositories. If you do not wish credentials to be required when interacting with github through git, simply create
a SSH key with no password.

== Configuring the .netrc file ==
The .netrc file was developed initially for storage of user credentials to permit autologin to remote FTP hosts. It must
be stored in the user's home directory. eg: /home/david/.netrc

It is a good idea to make sure that only the user has read/write access to this file, so be sure to run the following
chmod command on the .netrc file once populated _chmod 600 .netrc_ 

-----------------------------------------------------
david@David-Netbook:~$ ls -al .netrc
-rw------- 1 david users 67 Sep  8 20:59 .netrc
-----------------------------------------------------

The following is an example layout for adding your bitbucket credentials to the .netrc file.

-----------------------------------------------------
machine bitbucket.org
login yourbitbucketusername 
password yourbitbucketpassword
-----------------------------------------------------

This should now take effect immediately. When interacting with bitbucket.org through git, it should no longer ask you
for a username or password for the site.

<<<
== Bibliography: ==

[bibliography]
- [[[mavetju]]] 'How to use ftp in combination with .netrc', Edwin Groothuis. 2012. http://www.mavetju.org/unix/netrc.php
- [[[linuxabout]]] 'Linux/Unix Command: netrc', Juergen Haas. 2012. http://linux.about.com/library/cmd/blcmdl5_netrc.htm
