require 'bundler'

begin
  require 'bundler'
rescue Exception => e
  puts 'bundler gem not found, please install bundler and try again.'
  exit
end

Bundler::GemHelper.install_tasks

task :default => 'menu'

task :menu do
  puts welcomeMsg = <<-MSG
rake build    # Build asciirock-x.x.x.gem into the pkg directory
rake install  # Build and install asciirock-x.x.x.gem into system gems
rake release  # Create tag vx.x.x and build and push asciirock-x.x.x.gem to http://rubygems.org/
rake test     # Run the unit testing suite on this gem.
MSG
end

desc "Run the unit testing suite on this gem."
task :test do
  
  require "./test/test_helper.rb"

end
